server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?userSSL=false&characterEncoding=utf8
    name: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    
# 显示sql
  jpa:
    show-sql: true